config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, path: 'admin_users', controllers: {
    passwords: 'admin_users/passwords',
    sessions: 'admin_users/sessions'
  }
  devise_for :users, path: 'users', controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  root to: 'home#index'

  resources :password_attachments, only: [] do
    member do
      get :form
      post :download
    end
  end

  namespace :admin do
    root to: 'pages#index'
    resources :styles, only: [:index] do
      collection do
        put :update
        post :reset
      end
    end
    resources :settings, only: [:index] do
      collection do
        put :update
        post :reset
      end
    end
    resource :my_account, only: [:edit, :update]
    resources :pages, except: [:show]
    resources :attachments do
      collection do
        post :batch
      end
    end
    resources :courses, except: :new do
      resources :works
      resources :grades, only: [:index, :create]
      resources :messages, only: [:new, :create]
      member do
        get :grades_csv
      end
    end
    resources :users, only: [:index, :update, :destroy] do
      collection do
        delete :batch_delete
      end
    end
    resources :admin_users, except: [:show]
    resources :groups, only: [:index, :create, :update, :destroy]
    resources :courses_users, only: [:create, :destroy]
    post 'page_positions/:page_id/:direction', to: 'page_positions#create', as: 'page_positions'
    post 'course_positions/:course_id/:direction', to: 'course_positions#create', as: 'course_positions'
    resource :homepage, only: [:edit, :update]
    resources :attachment_courses, only: [:create, :destroy]
  end

  namespace :student do
    resources :attachments, only: [:index, :new, :create, :destroy, :update]
    resources :grades, only: [:index]
    resource :my_account, only: [:edit, :update]
  end

  resources :pages, only: :show do
    member do
      get :new_password
      post :set_password
    end
  end
end

app/models/attachment.rb
# frozen_string_literal: true

class Attachment < ApplicationRecord
  belongs_to :userable, polymorphic: true
  belongs_to :course, optional: true

  has_attached_file :attachment,
                    url: '/system/:attachment/:id_partition/:username_:filename',
                    path: ':rails_root/public/system/:attachment/:id_partition/:username_:filename'

  validates :attachment, attachment_presence: true
  do_not_validate_attachment_file_type :attachment

  def addable_courses
    Course.where.not(id: course_ids).order('lower(name)')
  end

  def name_with_user
    "#{userable.last_name}#{userable.first_name.first}"
  end

  Paperclip.interpolates :username do |attachment, _style|
    attachment.instance.name_with_user
  end
end

app/controllers/admin/attachments_controller.rb
# frozen_string_literal: true

module Admin
  class AttachmentsController < AdminController
    include ActionController::Streaming
    include Zipline

    def create
      @attachment = Attachment.new(attachment_params.merge(userable: current_admin_user))
      if @attachment.save
        redirect_to admin_attachments_path, notice: 'Uploaded!'
      else
        render :new
      end
    end

    def index # rubocop:disable Metrics/AbcSize, Metrics/MethodLength
      @my_attachments = current_admin_user.attachments.order(:created_at)
      if current_admin_user.super_admin?
        @teachers_attachments = Attachment.where(userable_type: AdminUser.name)
                                          .where.not(userable_id: current_admin_user.id)
                                          .order(:created_at)
      end
      @students_attachments = if current_admin_user.super_admin?
                                Attachment.where(userable_type: User.name).order(:created_at)
                              else
                                Attachment.where(userable_type: User.name, course: current_admin_user.courses).order(:created_at) # rubocop:disable Metrics/LineLength
                              end
    end

    def new
      @attachment = Attachment.new
      @courses = courses
    end

    def edit
      @attachment = Attachment.find(params[:id])
      @courses = courses
    end

    def update
      @attachment = Attachment.find(params[:id])
      authorize(@attachment)
      if @attachment.update(attachment_params)
        redirect_to admin_attachments_path, notice: 'Attachment updated'
      else
        render :edit
      end
    end

    def destroy
      attachment = Attachment.find(params[:id])
      authorize(attachment)
      attachment.destroy
      redirect_to admin_attachments_path, notice: I18n.t('flashes.file_destroyed')
    end

    def batch # rubocop:disable Metrics/AbcSize, Metrics/MethodLength
      return redirect_to admin_attachments_path, alert: 'No attachments selected' if params[:attachments].blank? # rubocop:disable Metrics/LineLength
      attachments = Attachment.where(id: params[:attachments][:ids])
      if params[:delete]
        attachments.each do |attachment|
          raise Pundit::NotAuthorized unless AttachmentPolicy.new(current_admin_user, attachment).destroy? # rubocop:disable Metrics/LineLength
          attachment.destroy
        end
        redirect_to admin_attachments_path, notice: I18n.t('flashes.files_destroyed')
      elsif params[:download]
        files = attachments.map { |attachment| [attachment.attachment, attachment.attachment_file_name] } # rubocop:disable Metrics/LineLength
        zipline(files, 'files.zip')
      end
    end

    private

    def courses
      if current_admin_user.super_admin?
        Course.order('lower(name)')
      else
        current_admin_user.courses.order('lower(name)')
      end
    end

    def attachment_params
      params.require(:attachment).permit(:attachment, :course_id, :password)
    end
  end
end

app/controllers/student/attachments_controller.rb
# frozen_string_literal: true

module Student
  class AttachmentsController < BaseController
    def index
      @user_attachments = current_user.attachments.order(:created_at)
      @admin_users_attachments = Attachment.where(userable_type: AdminUser.name, course: current_user.courses) # rubocop:disable Metrics/LineLength
                                           .order(:created_at)
    end

    def new
      @attachment = Attachment.new
    end

    def create
      @attachment = Attachment.new(attachment_params)
      @attachment.userable = current_user
      if @attachment.save
        redirect_to student_attachments_path, notice: I18n.t('flashes.file_uploaded')
      else
        render :new
      end
    end

    def update
      @attachment = Attachment.find(params[:id])
      @attachment.update(attachment_params) if @attachment.userable == current_user
    end

    def destroy
      attachment = Attachment.find(params[:id])
      if attachment.userable == current_user && attachment.destroy
        redirect_to student_attachments_path, notice: I18n.t('flashes.file_uploaded')
      else
        redirect_to student_attachments_path, alert: attachment.errors.full_messages.join(', ')
      end
    end

    private

    def attachment_params
      params.require(:attachment).permit(:attachment, :course_id)
    end
  end
end

app/views/admin/attachments/_attachment_courses.slim
- attachment_courses.joins(:course).order('lower(courses.name)').each do |attachment_course|
  li
    =' attachment_course.course.name
    = link_to '', admin_attachment_course_path(attachment_course), class: 'glyphicon glyphicon-remove text-danger', remote: true, method: :delete

app/views/admin/attachments/_courses_select_options.slim
option Add course
= options_from_collection_for_select(available_courses, :id, :name)

app/views/admin/attachments/_form.slim
= form_for @new_attachment, url: admin_attachments_path, html: { multipart: true } do |f|
  = f.file_field :attachment
  br
  = f.submit class: 'btn btn-default'

app/views/admin/attachments/_table.slim
- if attachments.count > 0
  = form_for :attachments, url: batch_admin_attachments_path do |f|
    table.table.table-striped.sortable
      thead
        tr
          th data={defaultsort: 'disabled'}
            input.select-all type='checkbox'
          th= Attachment.human_attribute_name(:attachment_file_name)
          th data={defaultsort: 'disabled'}
            = t('.course')
          th= t('.uploaded_by')
          th= Attachment.human_attribute_name(:attachment_file_size)
          th= Attachment.human_attribute_name(:created_at)
          th data={defaultsort: 'disabled'} colspan='2'
            = t('.actions')
      tbody
        - attachments.each do |attachment|
          tr
            td 
              - if policy(attachment).destroy? 
                = f.check_box :ids, {multiple: true}, attachment.id, false
            td= link_to attachment.attachment_file_name, attachment.password.blank? ? attachment.attachment.url : form_password_attachment_path(attachment)
            td= attachment.course&.name
            td= attachment.userable.email
            td= attachment.attachment_file_size / 1000
            td= attachment.created_at.localtime
            td
              = link_to t('.edit'), edit_admin_attachment_path(attachment) if policy(attachment).update?
            td
              = link_to t('.delete'), admin_attachment_path(attachment), method: :delete if policy(attachment).destroy?
    .buttons
      = f.submit 'Download selected', class: 'btn btn-default', name: :download
      = f.submit 'Delete selected', class: 'btn btn-danger', name: :delete
- else
  | No attachments

app/views/admin/attachments/edit.slim
h2 You are editing #{@attachment.attachment_file_name}

= simple_form_for [:admin, @attachment] do |f|
  = f.association :course, collection: @courses
  = f.input :password, as: :string
  = f.button :submit

app/views/admin/attachments/index.slim
.attachments
  h2 My uploads
  = render partial: 'table', locals: {attachments: @my_attachments}

- if current_admin_user.super_admin?
  .attachments
    h2 Teachers' uploads
    = render partial: 'table', locals: {attachments: @teachers_attachments}

.attachments
  h2 Students' uploads
  = render partial: 'table', locals: {attachments: @students_attachments}

app/views/admin/attachments/new.slim
= simple_form_for [:admin, @attachment] do |f|
  = f.association :course, collection: @courses
  = f.input :password, as: :string
  = f.input :attachment
  = f.button :submit