config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, path: 'admin_users', controllers: {
    passwords: 'admin_users/passwords',
    sessions: 'admin_users/sessions'
  }
  devise_for :users, path: 'users', controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  root to: 'home#index'

  resources :password_attachments, only: [] do
    member do
      get :form
      post :download
    end
  end

  namespace :admin do
    root to: 'pages#index'
    resources :styles, only: [:index] do
      collection do
        put :update
        post :reset
      end
    end
    resources :settings, only: [:index] do
      collection do
        put :update
        post :reset
      end
    end
    resource :my_account, only: [:edit, :update]
    resources :pages, except: [:show]
    resources :attachments do
      collection do
        post :batch
      end
    end
    resources :courses, except: :new do
      resources :works
      resources :grades, only: [:index, :create]
      resources :messages, only: [:new, :create]
      member do
        get :grades_csv
      end
    end
    resources :users, only: [:index, :update, :destroy] do
      collection do
        delete :batch_delete
      end
    end
    resources :admin_users, except: [:show]
    resources :groups, only: [:index, :create, :update, :destroy]
    resources :courses_users, only: [:create, :destroy]
    post 'page_positions/:page_id/:direction', to: 'page_positions#create', as: 'page_positions'
    post 'course_positions/:course_id/:direction', to: 'course_positions#create', as: 'course_positions'
    resource :homepage, only: [:edit, :update]
    resources :attachment_courses, only: [:create, :destroy]
  end

  namespace :student do
    resources :attachments, only: [:index, :new, :create, :destroy, :update]
    resources :grades, only: [:index]
    resource :my_account, only: [:edit, :update]
  end

  resources :pages, only: :show do
    member do
      get :new_password
      post :set_password
    end
  end
end

app/views/layouts/admin/_navbar.slim
nav.navbar.navbar-default
  = render partial: 'layouts/shared/flashes'
  .container-fluid
    .navbar-header
      = render partial: 'layouts/shared/nav_burger'
      = link_to t('.homepage'), root_path, class: 'navbar-brand'
    #navbar-collapse.collapse.navbar-collapse
      ul.nav.navbar-nav
        = render partial: 'layouts/admin/navbar_menu_item', locals: {scope: 'pages', label: t('.pages'), items: pages_menu_items}
        - if policy(Course).index?
          li class= (admin_active_class('courses') ? 'active' : '')
            = link_to t('.courses'), admin_courses_path
        li class= (admin_active_class('users') ? 'active' : '')
          = link_to t('.students'), admin_users_path
        - if policy(AdminUser).create?
          = render partial: 'layouts/admin/navbar_menu_item', locals: {scope: 'admin_users', label: t('.teachers'), items: teachers_menu_items}
        - if policy(Group).index?
          li class= (admin_active_class('groups') ? 'active' : '')
            = link_to t('.groups'), admin_groups_path

        = render partial: 'layouts/admin/navbar_menu_item', locals: {scope: 'attachments', label: t('.files'), items: files_menu_items}
        - if policy(Setting).index?
          = render partial: 'layouts/admin/navbar_menu_item', locals: {scope: 'styles', label: t('.settings'), items: settings_menu_items}
        li class= (admin_active_class('my_accounts') ? 'active' : '')
          = link_to t('.my_account'), edit_admin_my_account_path

      ul.nav.navbar-nav.navbar-right
        li= link_to t('layouts.sidebar.sign_out'), destroy_admin_user_session_path, method: :delete

app/views/layouts/admin/_navbar_menu_item.slim
li.dropdown class= (admin_active_class(scope) ? 'active' : '')
  a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button'
    => label
    span.caret
  ul.dropdown-menu
    - items.each do |item|
      li= link_to item[:label], item[:path]