config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, path: 'admin_users', controllers: {
    passwords: 'admin_users/passwords',
    sessions: 'admin_users/sessions'
  }
  devise_for :users, path: 'users', controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  root to: 'home#index'

  resources :password_attachments, only: [] do
    member do
      get :form
      post :download
    end
  end

  namespace :admin do
    root to: 'pages#index'
    resources :styles, only: [:index] do
      collection do
        put :update
        post :reset
      end
    end
    resources :settings, only: [:index] do
      collection do
        put :update
        post :reset
      end
    end
    resource :my_account, only: [:edit, :update]
    resources :pages, except: [:show]
    resources :attachments do
      collection do
        post :batch
      end
    end
    resources :courses, except: :new do
      resources :works
      resources :grades, only: [:index, :create]
      resources :messages, only: [:new, :create]
      member do
        get :grades_csv
      end
    end
    resources :users, only: [:index, :update, :destroy] do
      collection do
        delete :batch_delete
      end
    end
    resources :admin_users, except: [:show]
    resources :groups, only: [:index, :create, :update, :destroy]
    resources :courses_users, only: [:create, :destroy]
    post 'page_positions/:page_id/:direction', to: 'page_positions#create', as: 'page_positions'
    post 'course_positions/:course_id/:direction', to: 'course_positions#create', as: 'course_positions'
    resource :homepage, only: [:edit, :update]
    resources :attachment_courses, only: [:create, :destroy]
  end

  namespace :student do
    resources :attachments, only: [:index, :new, :create, :destroy, :update]
    resources :grades, only: [:index]
    resource :my_account, only: [:edit, :update]
  end

  resources :pages, only: :show do
    member do
      get :new_password
      post :set_password
    end
  end
end

app/models/work.rb
# frozen_string_literal: true

class Work < ApplicationRecord
  belongs_to :course
  has_many :grades, dependent: :destroy

  validates :name, presence: true
end

app/controllers/admin/works_controller.rb
# frozen_string_literal: true

module Admin
  class WorksController < AdminController
    def index
      @course = Course.find(params[:course_id])
      @works = @course.works.order(:name)
    end

    def create
      work = Work.new(work_params)
      work.course = Course.find(params[:course_id])
      if work.save
        render create_success_response(work)
      else
        render_partial_to_json('admin/works/_form', :unprocessable_entity, work: work) # rubocop:disable Metrics/LineLength
      end
    end

    def update
      work = Work.find(params[:id])
      work.update(work_params)
    end

    def destroy
      work = Work.find(params[:id])
      work.destroy
      redirect_to admin_course_works_path(work.course), notice: "#{work.name} destroyed"
    end

    def show
      @work = Work.find(params[:id])
      authorize(@work)
    end

    private

    def create_success_response(work)
      {
        json: {
          table_partial: render_to_string('admin/works/_index_table',
                                          layout: false,
                                          locals: { works: work.course.works.order(:name), course: work.course }), # rubocop:disable Metrics/LineLength
          form_partial: render_to_string('admin/works/_form',
                                         layout: false,
                                         locals: { work: Work.new, course: work.course }) # rubocop:disable Metrics/LineLength
        }, status: :ok
      }
    end

    def work_params
      params.require(:work).permit(:name)
    end
  end
end

app/views/admin/works/_form.slim
= simple_form_for [:admin, course, work], remote: true do |f|
  = f.input :name
  = f.button :submit

app/views/admin/works/_index_table.slim
- if works.size == 0
  #no-works.alert.alert-info= t('.no_works')

table#works-table.table.table-striped.sortable
  - if works.size > 0
    thead
      tr
        th= Work.human_attribute_name(:name)
        th data={defaultsort: 'disabled'}
        th data={defaultsort: 'disabled'}
    tbody
      - works.each do |work|
        tr
          td= best_in_place work, :name, as: :input, url: admin_course_work_path(course, work)
          td= link_to t('.delete'), admin_course_work_path(course, work), method: :delete

app/views/admin/works/_new_grade_form.slim
= simple_form_for [:admin, grade], remote: true do |f|
  = f.input :work_id, as: :hidden
  = f.association :user, \
                  collection: User.order_by_last_name \
                                  .joins(:courses) \
                                  .where('courses.id = ?', grade.work.course_id) \
                                  .where.not(id: grade.work.grades.pluck(:user_id)) \
                                  .map { |u| ["#{u.full_name} (index_number: #{u.index_number})", u.id] }
  = f.input :value
  = f.button :submit

app/views/admin/works/_show_grades_table.slim
table#grades_table.table.table-striped.sortable
  - if work.grades.exists?
    thead
      tr
        th= t('.student_name')
        th= User.human_attribute_name(:index_number)
        th= t('.grade')
        th data={defaultsort: 'disabled'}
          = t('.actions')
    tbody
      - work.grades.order_by_user_last_name.each do |grade|
        tr
          td= "#{grade.user.last_name} #{grade.user.first_name}"
          td= grade.user.index_number
          td= best_in_place grade, :value, as: :input, url: admin_grade_path(grade)
          td= link_to t('.delete'), admin_grade_path(grade), method: :delete

app/views/admin/works/index.slim
h2 Works for #{@course.name}
.row
  .col-xs-12.col-md-6
    p= t('.click_to_edit')
    = render partial: 'index_table', locals: {works: @works, course: @course}
.row
  .col-xs-7.col-md-5
    = render partial: 'form', locals: {work: Work.new, course: @course}

app/views/admin/works/show.slim
.row
  .col-sm-12
    h2= "#{Work.model_name}: #{@work.name}"
    h3= "#{Course.model_name}: #{@work.course.name}"

.row
  .col-sm-12
    h4 Grades
    - if @work.grades.count == 0
      #no-grades.alert.alert-info= t('.no_grades')
    = render partial: 'show_grades_table', locals: {work: @work}
    = render partial: 'new_grade_form', locals: {grade: Grade.new(work: @work)}